In [ ]:
# the WELFake Dataset and modify the dataset for our multimodal

In [ ]:
import pandas as pd

file_path = "WELFake_Dataset.csv"

welfake = pd.read_csv(file_path)

print(welfake.shape)
welfake.head()

C:\Users\kruthi\.conda\New folder\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

(72134, 4)

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [ ]:
welfake["text"] = (
    welfake["title"].fillna("") + " " +
    welfake["text"].fillna("")
)

In [ ]:
welfake["image_path"] = None
welfake["audio_path"] = None
welfake["video_path"] = None
welfake["modality_mask"] = "[1,0,0,0]"

In [ ]:
welfake = welfake[
    ["text","image_path","audio_path","video_path","label","modality_mask"]
]

In [ ]:
welfake.reset_index(inplace=True)
welfake.rename(columns={"index":"id"}, inplace=True)

In [ ]:
save_path = "unified_welfake.csv"

welfake.to_csv(save_path, index=False)

print("Unified WELFake dataset saved")

Unified WELFake dataset saved

In [ ]:
# the Fakenews Dataset and modify the dataset for our multimodal

In [ ]:
buzz_fake = pd.read_csv("fakenewsnet/BuzzFeed_fake_news_content.csv")
buzz_real = pd.read_csv("fakenewsnet/BuzzFeed_real_news_content.csv")

buzz_fake["label"] = 1
buzz_real["label"] = 0

buzz = pd.concat([buzz_fake, buzz_real], ignore_index=True)

In [ ]:
polit_fake = pd.read_csv("fakenewsnet/PolitiFact_fake_news_content.csv")
polit_real = pd.read_csv("fakenewsnet/PolitiFact_real_news_content.csv")

polit_fake["label"] = 1
polit_real["label"] = 0

polit = pd.concat([polit_fake, polit_real], ignore_index=True)

In [ ]:
fakenewsnet = pd.concat([buzz, polit], ignore_index=True)

print(fakenewsnet.shape)
fakenewsnet.head()

(422, 13)

,id,title,text,url,top_img,authors,source,publish_date,movies,images,canonical_link,meta_data,label
0,Fake_1-Webpage,Proof The Mainstream Media Is Manipulating The...,I woke up this morning to find a variation of ...,http://www.addictinginfo.org/2016/09/19/proof-...,http://addictinginfo.addictinginfoent.netdna-c...,Wendy Gittleson,http://www.addictinginfo.org,{'$date': 1474243200000},NaN,"http://i.imgur.com/JeqZLhj.png,http://addictin...",http://addictinginfo.com/2016/09/19/proof-the-...,"{""publisher"": ""Addicting Info | The Knowledge ...",1
1,Fake_10-Webpage,Charity: Clinton Foundation Distributed “Water...,Former President Bill Clinton and his Clinton ...,http://eaglerising.com/36899/charity-clinton-f...,http://eaglerising.com/wp-content/uploads/2016...,View All Posts,http://eaglerising.com,{'$date': 1474416521000},NaN,http://constitution.com/wp-content/uploads/201...,http://eaglerising.com/36899/charity-clinton-f...,"{""description"": ""The possibility that CHAI dis...",1
2,Fake_11-Webpage,A Hillary Clinton Administration May be Entire...,After collapsing just before trying to step in...,http://eaglerising.com/36880/a-hillary-clinton...,http://eaglerising.com/wp-content/uploads/2016...,"View All Posts,Tony Elliott",http://eaglerising.com,{'$date': 1474416638000},NaN,http://constitution.com/wp-content/uploads/201...,http://eaglerising.com/36880/a-hillary-clinton...,"{""description"": ""Hillary Clinton may be the fi...",1
3,Fake_12-Webpage,Trump’s Latest Campaign Promise May Be His Mos...,"Donald Trump is, well, deplorable. He’s sugges...",http://www.addictinginfo.org/2016/09/19/trumps...,http://addictinginfo.addictinginfoent.netdna-c...,John Prager,http://www.addictinginfo.org,{'$date': 1474243200000},NaN,"http://i.imgur.com/JeqZLhj.png,http://2.gravat...",http://addictinginfo.com/2016/09/19/trumps-lat...,"{""publisher"": ""Addicting Info | The Knowledge ...",1
4,Fake_13-Webpage,Website is Down For Maintenance,Website is Down For Maintenance,http://www.proudcons.com/clinton-foundation-ca...,NaN,NaN,http://www.proudcons.com,NaN,NaN,NaN,NaN,"{""og"": {""url"": ""http://www.proudcons.com"", ""ty...",1

In [ ]:
fakenewsnet["text"] = (
    fakenewsnet["title"].fillna("") + " " +
    fakenewsnet["text"].fillna("")
)

In [ ]:
# Add missing modality columns
fakenewsnet["image_path"] = None
fakenewsnet["audio_path"] = None
fakenewsnet["video_path"] = None

# TEXT modality only
fakenewsnet["modality_mask"] = "[1,1,0,0]"

In [ ]:
fakenewsnet = fakenewsnet[
    ["text","image_path","audio_path","video_path","label","modality_mask"]
]

In [ ]:
save_path = "unified_fakenewsnet.csv"

fakenewsnet.to_csv(save_path, index=False)

print("FakeNewsNet unified dataset saved")

FakeNewsNet unified dataset saved

In [ ]:
# the FakeAV Dataset and modify the dataset for our multimodal

In [ ]:
import os
import pandas as pd

root_path = r"C:\Users\kruthi\Desktop\AI_project\fakeav\frames"

data = []

for top_folder in os.listdir(root_path):

    top_path = os.path.join(root_path, top_folder)

    if not os.path.isdir(top_path):
        continue

    # LABEL LOGIC
    if "RealVideo-RealAudio" in top_folder:
        label = "real"
    else:
        label = "fake"

    # Walk through deep folders
    for root, dirs, files in os.walk(top_path):

        video_id = os.path.basename(root)

        for file in files:
            if file.lower().endswith((".jpg", ".png")):

                frame_path = os.path.join(root, file)

                data.append({
                    "frame_path": frame_path,
                    "label": label,
                    "video_id": video_id
                })

fakeav_df = pd.DataFrame(data)

print(fakeav_df.shape)
fakeav_df.head()

(21560, 3)

                                          frame_path label video_id
0  C:\Users\kruthi\Desktop\AI_project\fakeav\fram...  fake  id00076
1  C:\Users\kruthi\Desktop\AI_project\fakeav\fram...  fake  id00076
2  C:\Users\kruthi\Desktop\AI_project\fakeav\fram...  fake  id00076
3  C:\Users\kruthi\Desktop\AI_project\fakeav\fram...  fake  id00076
4  C:\Users\kruthi\Desktop\AI_project\fakeav\fram...  fake  id00076

In [ ]:
fakeav_df['label'].value_counts()

label
fake    21060
real      500
Name: count, dtype: int64

In [ ]:
import pandas as pd

fakenewsnet = pd.read_csv("unified_fakenewsnet.csv")

# Add id column
fakenewsnet["id"] = range(len(fakenewsnet))

# Reorder columns
fakenewsnet = fakenewsnet[
    ["id","text","image_path","audio_path",
     "video_path","label","modality_mask"]
]

# Save fixed version
fakenewsnet.to_csv("fixed_fakenewsnet.csv", index=False)

In [ ]:
import pandas as pd

meta_path = r"C:\Users\kruthi\Desktop\AI_project\fakeav\FakeAVCeleb_v1.2\meta_data.csv"

meta = pd.read_csv(meta_path)

print(meta.columns)
print(meta.head())

Index(['source', 'target1', 'target2', 'method', 'category', 'type', 'race',
       'gender', 'path', 'Unnamed: 9'],
      dtype='object')
    source target1 target2 method category                 type     race  \
0  id00076       -       -   real        A  RealVideo-RealAudio  African
1  id00166       -       -   real        A  RealVideo-RealAudio  African
2  id00173       -       -   real        A  RealVideo-RealAudio  African
3  id00366       -       -   real        A  RealVideo-RealAudio  African
4  id00391       -       -   real        A  RealVideo-RealAudio  African

  gender       path                                         Unnamed: 9
0    men  00109.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id...
1    men  00010.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id...
2    men  00118.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id...
3    men  00118.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id...
4    men  00052.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id...

In [ ]:
import pandas as pd
import os

# ==============================
# PATHS (EDIT ONLY THESE)
# ==============================

meta_path = r"C:\Users\kruthi\Desktop\AI_project\fakeav\FakeAVCeleb_v1.2\meta_data.csv"

# NEW ROOTS (FINAL STORAGE LOCATION)
video_root = r"D:\Datasets\FakeAVCeleb_v1.2"
audio_root = r"D:\Datasets\audio"

save_path = r"C:\Users\kruthi\Desktop\AI_project\fakeav_welfake_format.csv"


# ==============================
# LOAD METADATA
# ==============================

meta = pd.read_csv(meta_path)

meta = meta.drop(columns=["Unnamed: 9"], errors="ignore")


# ==============================
# LABEL CREATION
# ==============================

meta["label"] = meta["type"].apply(
    lambda x: 0 if x == "RealVideo-RealAudio" else 1
)


# ==============================
# REQUIRED COLUMNS
# ==============================

# No text modality
meta["text"] = ""

# ---------- VIDEO PATH FIX ----------
# Keeps full folder structure
meta["video_path"] = meta["path"].apply(
    lambda x: os.path.join(video_root, x.split("FakeAVCeleb_v1.2")[-1].lstrip("\\/"))
)

# ---------- AUDIO PATH FIX ----------
meta["audio_path"] = meta["path"].str.replace(".mp4", ".wav", regex=False)

meta["audio_path"] = meta["audio_path"].apply(
    lambda x: os.path.join(audio_root, os.path.basename(x))
)

# No image modality
meta["image_path"] = ""

# modality mask → AUDIO + VIDEO
meta["modality_mask"] = "[0,0,1,1]"

# Create IDs
meta["id"] = range(len(meta))


# ==============================
# MATCH WELFAKE FORMAT
# ==============================

fakeav_welfake_format = meta[
    [
        "id",
        "text",
        "image_path",
        "audio_path",
        "video_path",
        "label",
        "modality_mask",
    ]
]


# ==============================
# SAVE
# ==============================

fakeav_welfake_format.to_csv(save_path, index=False)

print("✅ FakeAVCeleb converted with ROOT FIX!")
print(fakeav_welfake_format.head())

✅ FakeAVCeleb converted with ROOT FIX!
   id text image_path                   audio_path  \
0   0                  D:\Datasets\audio\00109.wav
1   1                  D:\Datasets\audio\00010.wav
2   2                  D:\Datasets\audio\00118.wav
3   3                  D:\Datasets\audio\00118.wav
4   4                  D:\Datasets\audio\00052.wav

                               video_path  label modality_mask
0  D:\Datasets\FakeAVCeleb_v1.2\00109.mp4      0     [0,0,1,1]
1  D:\Datasets\FakeAVCeleb_v1.2\00010.mp4      0     [0,0,1,1]
2  D:\Datasets\FakeAVCeleb_v1.2\00118.mp4      0     [0,0,1,1]
3  D:\Datasets\FakeAVCeleb_v1.2\00118.mp4      0     [0,0,1,1]
4  D:\Datasets\FakeAVCeleb_v1.2\00052.mp4      0     [0,0,1,1]

In [ ]:
#combine the datasets

In [ ]:
import pandas as pd

df = pd.read_csv("FINAL_MULTIMODAL_DATASET.csv")

def has_text(row):
    return isinstance(row["text"], str) and row["text"].strip() != ""

def has_image(row):
    return isinstance(row["image_path"], str) and row["image_path"].strip() != ""

def has_audio(row):
    return isinstance(row["audio_path"], str) and row["audio_path"].strip() != ""

def has_video(row):
    return isinstance(row["video_path"], str) and row["video_path"].strip() != ""

# Assign group label
def get_group(row):
    t = has_text(row)
    i = has_image(row)
    a = has_audio(row)
    v = has_video(row)

    if t and not i and not a and not v:
        return "text_only"
    elif t and i and not a and not v:
        return "text_image"
    elif a and v:
        return "audio_video"
    else:
        return "other"

df["modality_group"] = df.apply(get_group, axis=1)

C:\Users\kruthi\AppData\Local\Temp\ipykernel_20540\2200817262.py:3: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("FINAL_MULTIMODAL_DATASET.csv")

In [ ]:
# reducing the the large dataset to a small dataset to train and test

In [ ]:
N = len(df)
n_text = int(0.2 * N)
n_text_image = int(0.3 * N)
n_audio_video = int(0.5 * N)

# Sample each group
text_only_df = df[df["modality_group"] == "text_only"].sample(n=min(n_text, len(df[df["modality_group"] == "text_only"])), random_state=42)
text_image_df = df[df["modality_group"] == "text_image"].sample(n=min(n_text_image, len(df[df["modality_group"] == "text_image"])), random_state=42)
audio_video_df = df[df["modality_group"] == "audio_video"].sample(n=min(n_audio_video, len(df[df["modality_group"] == "audio_video"])), random_state=42)

# Combine
balanced_df = pd.concat([text_only_df, text_image_df, audio_video_df]).reset_index(drop=True)
print("Balanced multimodal dataset size:", len(balanced_df))
print(balanced_df["modality_group"].value_counts())

Balanced multimodal dataset size: 387321
modality_group
text_image     219453
text_only      146302
audio_video     21566
Name: count, dtype: int64

# reduce the dataset size

In [ ]:
n_audio_video = 21566           # 50%
n_text_image = int(0.3 / 0.5 * n_audio_video)  # 30% => 12939
n_text_only = int(0.2 / 0.5 * n_audio_video)   # 20% => 8626

In [ ]:
text_only_df = balanced_df[balanced_df["modality_group"] == "text_only"].sample(n=n_text_only, random_state=42)
text_image_df = balanced_df[balanced_df["modality_group"] == "text_image"].sample(n=n_text_image, random_state=42)
audio_video_df = balanced_df[balanced_df["modality_group"] == "audio_video"].sample(n=n_audio_video, random_state=42)

# Combine
final_df = pd.concat([text_only_df, text_image_df, audio_video_df]).reset_index(drop=True)

print("Downsampled dataset size:", len(final_df))
print(final_df["modality_group"].value_counts())

Downsampled dataset size: 43131
modality_group
audio_video    21566
text_image     12939
text_only       8626
Name: count, dtype: int64

In [ ]:
import pandas as pd

df = pd.read_csv("FINAL_MULTIMODAL_DATASET.csv")

print("Original Dataset Size:", len(df))

C:\Users\kruthi\AppData\Local\Temp\ipykernel_22888\843153906.py:3: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("FINAL_MULTIMODAL_DATASET.csv")

Original Dataset Size: 731510

In [ ]:
# check the split of the data for image, video,text and audio

In [ ]:
def has_text(row):
    return isinstance(row["text"], str) and row["text"].strip() != ""

def has_image(row):
    return isinstance(row["image_path"], str) and row["image_path"].strip() != ""

def has_audio(row):
    return isinstance(row["audio_path"], str) and row["audio_path"].strip() != ""

def has_video(row):
    return isinstance(row["video_path"], str) and row["video_path"].strip() != ""

def get_group(row):
    t = has_text(row)
    i = has_image(row)
    a = has_audio(row)
    v = has_video(row)

    if t and not i and not a and not v:
        return "text_only"
    elif t and i and not a and not v:
        return "text_image"
    elif a and v:
        return "audio_video"
    else:
        return "other"

df["modality_group"] = df.apply(get_group, axis=1)

In [ ]:
audio_video_df = df[df["modality_group"] == "audio_video"]
text_image_df = df[df["modality_group"] == "text_image"]
text_only_df = df[df["modality_group"] == "text_only"]

n_audio_video = len(audio_video_df)

n_text_image = int(0.3 / 0.5 * n_audio_video)
n_text_only = int(0.2 / 0.5 * n_audio_video)

print("\nTarget Samples:")
print("audio_video:", n_audio_video)
print("text_image:", n_text_image)
print("text_only:", n_text_only)

Target Samples:
audio_video: 21566
text_image: 12939
text_only: 8626

In [ ]:
text_only_sample = text_only_df.sample(n=n_text_only, random_state=42)
text_image_sample = text_image_df.sample(n=n_text_image, random_state=42)
audio_video_sample = audio_video_df.sample(n=n_audio_video, random_state=42)

balanced_df = pd.concat([
    text_only_sample,
    text_image_sample,
    audio_video_sample
]).reset_index(drop=True)

In [ ]:
print("\nFinal Modality Distribution:")
print(balanced_df["modality_group"].value_counts(normalize=True))

Final Modality Distribution:
modality_group
audio_video    0.500012
text_image     0.299993
text_only      0.199995
Name: proportion, dtype: float64

In [ ]:
print("\nReal vs Fake Distribution:")
print(balanced_df["label"].value_counts())
print(balanced_df["label"].value_counts(normalize=True))

Real vs Fake Distribution:
label
1    30626
0    12505
Name: count, dtype: int64
label
1    0.710069
0    0.289931
Name: proportion, dtype: float64

In [ ]:
balanced_df.to_csv("balanced_multimodal_welfake.csv", index=False)

print("\n✅ Balanced dataset saved!")

✅ Balanced dataset saved!

In [ ]:
# saving the final dataset for the next steps as balanced_multimodal_welfake.csv

In [ ]:
# now starts the embedding

In [ ]:
import pandas as pd
import torch
import numpy as np
import cv2
import librosa
from PIL import Image
from tqdm import tqdm

from sentence_transformers import SentenceTransformer
from transformers import (
    CLIPProcessor,
    CLIPModel,
    Wav2Vec2Processor,
    Wav2Vec2Model,
    VideoMAEImageProcessor,
    VideoMAEModel
)

import timm
import torchvision.transforms as transforms

In [ ]:
df = pd.read_csv("balanced_multimodal_welfake.csv")

print("Balanced dataset size:", len(df))

Balanced dataset size: 43131

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using:", device)

Using: cpu

In [ ]:
print("Loading models...")

# TEXT
text_model = SentenceTransformer("all-mpnet-base-v2").to(device)

# IMAGE
clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to(device)
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

dino_model = timm.create_model("vit_base_patch14_dinov2", pretrained=True)
dino_model.to(device).eval()

dino_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

# AUDIO
audio_processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base")
audio_model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base").to(device)

# VIDEO
video_processor = VideoMAEImageProcessor.from_pretrained("MCG-NJU/videomae-base")
video_model = VideoMAEModel.from_pretrained("MCG-NJU/videomae-base").to(device)

print("✅ Models Loaded")

Loading models...

C:\Users\kruthi\.conda\New folder\envs\multimodal\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\kruthi\.conda\New folder\envs\multimodal\lib\site-packages\transformers\configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

✅ Models Loaded

In [ ]:
text_features = []
image_features = []
audio_features = []
video_features = []

In [ ]:
def extract_text(text):
    if not isinstance(text, str) or text.strip()=="":
        return np.zeros(768)
    return text_model.encode(text)

In [ ]:
def extract_image(path):

    if not isinstance(path,str) or path.strip()=="":
        return np.zeros(512+768)

    try:
        image = Image.open(path).convert("RGB")

        clip_inputs = clip_processor(images=image,
                                     return_tensors="pt").to(device)

        clip_feat = clip_model.get_image_features(**clip_inputs)
        clip_feat = clip_feat.detach().cpu().numpy().flatten()

        img = dino_transform(image).unsqueeze(0).to(device)

        with torch.no_grad():
            dino_feat = dino_model.forward_features(img)

        dino_feat = dino_feat.mean(dim=1).cpu().numpy().flatten()

        return np.concatenate([clip_feat,dino_feat])

    except:
        return np.zeros(512+768)

In [ ]:
def extract_audio(path):

    if not isinstance(path,str) or path.strip()=="":
        return np.zeros(768)

    try:
        speech,_ = librosa.load(path,sr=16000)

        inputs = audio_processor(
            speech,
            sampling_rate=16000,
            return_tensors="pt"
        ).to(device)

        with torch.no_grad():
            outputs = audio_model(**inputs)

        emb = outputs.last_hidden_state.mean(dim=1)
        return emb.cpu().numpy().flatten()

    except:
        return np.zeros(768)

In [ ]:
def extract_video(path,num_frames=16):

    if not isinstance(path,str) or path.strip()=="":
        return np.zeros(768)

    try:
        cap=cv2.VideoCapture(path)
        frames=[]

        total=int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        step=max(total//num_frames,1)

        for i in range(0,total,step):
            cap.set(cv2.CAP_PROP_POS_FRAMES,i)
            ret,frame=cap.read()
            if not ret:
                break

            frame=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
            frames.append(frame)

            if len(frames)==num_frames:
                break

        cap.release()

        if len(frames)==0:
            return np.zeros(768)

        inputs=video_processor(frames,
                               return_tensors="pt").to(device)

        with torch.no_grad():
            outputs=video_model(**inputs)

        emb=outputs.last_hidden_state.mean(dim=1)

        return emb.cpu().numpy().flatten()

    except:
        return np.zeros(768)

In [ ]:
for _,row in tqdm(df.iterrows(),total=len(df)):

    text_features.append(
        extract_text(row.get("text",""))
    )

    image_features.append(
        extract_image(row.get("image_path",""))
    )

    audio_features.append(
        extract_audio(row.get("audio_path",""))
    )

    video_features.append(
        extract_video(row.get("video_path",""))
    )

 50%|████▉     | 21565/43131 [1:54:35<1:08:44,  5.23it/s]  C:\Users\kruthi\AppData\Local\Temp\ipykernel_22888\3153728749.py:7: UserWarning: PySoundFile failed. Trying audioread instead.
  speech,_ = librosa.load(path,sr=16000)
C:\Users\kruthi\.conda\New folder\envs\multimodal\lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
100%|██████████| 43131/43131 [3:37:41<00:00,  3.30it/s]

In [ ]:
np.save("text_embeddings.npy",np.array(text_features))
np.save("image_embeddings.npy",np.array(image_features))
np.save("audio_embeddings.npy",np.array(audio_features))
np.save("video_embeddings.npy",np.array(video_features))

# Save labels + metadata alignment
df.to_csv("embedding_metadata.csv",index=False)

print("✅ Embeddings Saved Successfully")

✅ Embeddings Saved Successfully

In [ ]:
# now the emebbings are saved as text_embedding.npy, image_embedding.npy, video_embedding.npy, audio_embedding.npy

In [ ]:
import pandas as pd
import numpy as np

# ======================================================
# 1. LOAD BALANCED DATASET
# ======================================================

CSV_PATH = "balanced_multimodal_welfake.csv"

df = pd.read_csv(CSV_PATH)

print("\n✅ Dataset Loaded")
print("Total Samples:", len(df))

# ======================================================
# 2. CHECK MODALITY DISTRIBUTION
# ======================================================

print("\n📊 Modality Distribution:")
print(df["modality_group"].value_counts())

# ======================================================
# 3. CHECK LABEL COLUMN
# ======================================================

print("\nColumns in Dataset:")
print(df.columns)

# ---- CHANGE THIS IF YOUR LABEL COLUMN NAME IS DIFFERENT ----
LABEL_COLUMN = "label"

# ======================================================
# 4. CONVERT LABELS → NUMERIC
# ======================================================

if df[LABEL_COLUMN].dtype == object:
    labels = df[LABEL_COLUMN].str.lower().map({
        "real": 0,
        "fake": 1
    }).values
else:
    labels = df[LABEL_COLUMN].astype(int).values

print("\n✅ Labels Converted")

# ======================================================
# 5. CHECK REAL vs FAKE BALANCE
# ======================================================

unique, counts = np.unique(labels, return_counts=True)

print("\n📊 Real vs Fake Distribution:")
for u, c in zip(unique, counts):
    name = "REAL" if u == 0 else "FAKE"
    print(f"{name}: {c}")

# ======================================================
# 6. SAVE LABELS
# ======================================================

np.save("labels.npy", labels)

print("\n✅ labels.npy saved!")

# ======================================================
# 7. VERIFY EMBEDDING MATCH (OPTIONAL BUT IMPORTANT)
# ======================================================

try:
    text_emb = np.load("text_embeddings.npy")

    print("\nChecking embedding alignment...")
    print("Labels shape:", labels.shape)
    print("Text embeddings shape:", text_emb.shape)

    assert len(labels) == len(text_emb)

    print("✅ Labels match embeddings!")

except Exception as e:
    print("\n⚠️ Embedding check skipped or mismatch:", e)

print("\n🎯 READY FOR CROSS-ATTENTION TRAINING")

✅ Dataset Loaded
Total Samples: 43131

📊 Modality Distribution:
modality_group
audio_video    21566
text_image     12939
text_only       8626
Name: count, dtype: int64

Columns in Dataset:
Index(['id', 'text', 'image_path', 'audio_path', 'video_path', 'label',
       'modality_mask', 'modality_group'],
      dtype='object')

✅ Labels Converted

📊 Real vs Fake Distribution:
REAL: 12505
FAKE: 30626

✅ labels.npy saved!

Checking embedding alignment...
Labels shape: (43131,)
Text embeddings shape: (43131, 768)
✅ Labels match embeddings!

🎯 READY FOR CROSS-ATTENTION TRAINING

In [ ]:
# we now have the labels.npy embeddings as well

In [ ]:
# applying cross attention to the embeddings

In [ ]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# ======================================================
# DEVICE
# ======================================================

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# ======================================================
# LOAD EMBEDDINGS
# ======================================================

text = np.load("text_embeddings.npy")
image = np.load("image_embeddings.npy")
audio = np.load("audio_embeddings.npy")
video = np.load("video_embeddings.npy")
labels = np.load("labels.npy")

print("Loaded embeddings:")
print(text.shape, image.shape, audio.shape, video.shape)

# ======================================================
# DATASET
# ======================================================

class MultimodalDataset(Dataset):
    def __init__(self, t, i, a, v, y):
        self.text = torch.tensor(t, dtype=torch.float32)
        self.image = torch.tensor(i, dtype=torch.float32)
        self.audio = torch.tensor(a, dtype=torch.float32)
        self.video = torch.tensor(v, dtype=torch.float32)
        self.labels = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return (
            self.text[idx],
            self.image[idx],
            self.audio[idx],
            self.video[idx],
            self.labels[idx],
        )

# ======================================================
# TRAIN TEST SPLIT
# ======================================================

X_train, X_test, I_train, I_test, A_train, A_test, V_train, V_test, y_train, y_test = train_test_split(
    text, image, audio, video, labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

train_dataset = MultimodalDataset(X_train, I_train, A_train, V_train, y_train)
test_dataset = MultimodalDataset(X_test, I_test, A_test, V_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

# ======================================================
# CROSS ATTENTION MODEL
# ======================================================
class CrossAttentionModel(nn.Module):

    def __init__(self, text_dim, image_dim, audio_dim, video_dim, hidden=512):
        super().__init__()

        # Projection layers
        self.text_proj = nn.Linear(text_dim, hidden)
        self.image_proj = nn.Linear(image_dim, hidden)
        self.audio_proj = nn.Linear(audio_dim, hidden)
        self.video_proj = nn.Linear(video_dim, hidden)

        # Cross Attention
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=hidden,
            num_heads=8,
            batch_first=True
        )

        # Classifier
        self.classifier = nn.Sequential(
            nn.Linear(hidden, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 2)
        )

    def forward(self, text, image, audio, video):

        # Project to same dimension
        t = self.text_proj(text).unsqueeze(1)
        i = self.image_proj(image).unsqueeze(1)
        a = self.audio_proj(audio).unsqueeze(1)
        v = self.video_proj(video).unsqueeze(1)

        # Concatenate non-text modalities
        other_modalities = torch.cat([i, a, v], dim=1)

        # STRICT CROSS ATTENTION
        fused, _ = self.cross_attn(
            query=t,
            key=other_modalities,
            value=other_modalities
        )

        fused = fused.squeeze(1)

        out = self.classifier(fused)

        return out

# ======================================================
# MODEL INIT
# ======================================================

model = CrossAttentionModel(
    text.shape[1],
    image.shape[1],
    audio.shape[1],
    video.shape[1]
).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# ======================================================
# TRAINING LOOP
# ======================================================

EPOCHS = 10

for epoch in range(EPOCHS):

    model.train()
    total_loss = 0

    for t, i, a, v, y in train_loader:

        t, i, a, v, y = (
            t.to(device),
            i.to(device),
            a.to(device),
            v.to(device),
            y.to(device),
        )

        optimizer.zero_grad()

        outputs = model(t, i, a, v)
        loss = criterion(outputs, y)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} Loss: {total_loss:.4f}")

# ======================================================
# EVALUATION
# ======================================================

model.eval()

preds = []
truths = []

with torch.no_grad():
    for t, i, a, v, y in test_loader:

        t, i, a, v = (
            t.to(device),
            i.to(device),
            a.to(device),
            v.to(device),
        )

        outputs = model(t, i, a, v)
        pred = torch.argmax(outputs, dim=1).cpu().numpy()

        preds.extend(pred)
        truths.extend(y.numpy())

print("\nAccuracy:", accuracy_score(truths, preds))
print("\nClassification Report:")
print(classification_report(truths, preds))

# ======================================================
# SAVE MODEL
# ======================================================

torch.save(model.state_dict(), "cross_attention_model.pth")

print("\n✅ Model saved!")

Using device: cpu
Loaded embeddings:
(43131, 768) (43131, 1280) (43131, 768) (43131, 768)
Epoch 1 Loss: 413.4695
Epoch 2 Loss: 321.4499
Epoch 3 Loss: 309.3159
Epoch 4 Loss: 298.1644
Epoch 5 Loss: 285.5413
Epoch 6 Loss: 276.7229
Epoch 7 Loss: 270.6178
Epoch 8 Loss: 267.2852
Epoch 9 Loss: 263.4790
Epoch 10 Loss: 260.7258

Accuracy: 0.9027471890576099

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.84      0.83      2501
           1       0.93      0.93      0.93      6126

    accuracy                           0.90      8627
   macro avg       0.88      0.88      0.88      8627
weighted avg       0.90      0.90      0.90      8627


✅ Model saved!

In [ ]:
# apllying gated fusion

In [ ]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# ======================================================
# DEVICE
# ======================================================

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# ======================================================
# LOAD EMBEDDINGS
# ======================================================

text = np.load("text_embeddings.npy")
image = np.load("image_embeddings.npy")
audio = np.load("audio_embeddings.npy")
video = np.load("video_embeddings.npy")
labels = np.load("labels.npy")

print("Loaded embeddings:")
print(text.shape, image.shape, audio.shape, video.shape)

# ======================================================
# DATASET
# ======================================================

class MultimodalDataset(Dataset):

    def __init__(self, t, i, a, v, y):

        self.text = torch.tensor(t, dtype=torch.float32)
        self.image = torch.tensor(i, dtype=torch.float32)
        self.audio = torch.tensor(a, dtype=torch.float32)
        self.video = torch.tensor(v, dtype=torch.float32)
        self.labels = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):

        return (
            self.text[idx],
            self.image[idx],
            self.audio[idx],
            self.video[idx],
            self.labels[idx]
        )

# ======================================================
# TRAIN TEST SPLIT
# ======================================================

X_train, X_test, I_train, I_test, A_train, A_test, V_train, V_test, y_train, y_test = train_test_split(
    text,
    image,
    audio,
    video,
    labels,
    test_size=0.2,
    stratify=labels,
    random_state=42
)

train_dataset = MultimodalDataset(X_train, I_train, A_train, V_train, y_train)
test_dataset = MultimodalDataset(X_test, I_test, A_test, V_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

# ======================================================
# GATED FUSION MODEL
# ======================================================

class GatedFusionModel(nn.Module):

    def __init__(self, text_dim, image_dim, audio_dim, video_dim, hidden=512):

        super().__init__()

        # Projection layers
        self.text_proj = nn.Linear(text_dim, hidden)
        self.image_proj = nn.Linear(image_dim, hidden)
        self.audio_proj = nn.Linear(audio_dim, hidden)
        self.video_proj = nn.Linear(video_dim, hidden)

        # Gate layers
        self.text_gate = nn.Linear(hidden, hidden)
        self.image_gate = nn.Linear(hidden, hidden)
        self.audio_gate = nn.Linear(hidden, hidden)
        self.video_gate = nn.Linear(hidden, hidden)

        self.sigmoid = nn.Sigmoid()

        # Classifier
        self.classifier = nn.Sequential(
            nn.Linear(hidden, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 2)
        )

    def forward(self, text, image, audio, video):

        # Projection
        t = self.text_proj(text)
        i = self.image_proj(image)
        a = self.audio_proj(audio)
        v = self.video_proj(video)

        # Gates
        gt = self.sigmoid(self.text_gate(t))
        gi = self.sigmoid(self.image_gate(i))
        ga = self.sigmoid(self.audio_gate(a))
        gv = self.sigmoid(self.video_gate(v))

        # Apply gates
        t = gt * t
        i = gi * i
        a = ga * a
        v = gv * v

        # Fusion
        fused = (t + i + a + v) / 4

        # Classification
        out = self.classifier(fused)

        return out

# ======================================================
# MODEL INIT
# ======================================================

model = GatedFusionModel(
    text.shape[1],
    image.shape[1],
    audio.shape[1],
    video.shape[1]
).to(device)

# Class weights for imbalance
class_weights = torch.tensor([1.7, 0.7]).to(device)

criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# ======================================================
# TRAINING
# ======================================================

EPOCHS = 10

for epoch in range(EPOCHS):

    model.train()
    total_loss = 0

    for t, i, a, v, y in train_loader:

        t = t.to(device)
        i = i.to(device)
        a = a.to(device)
        v = v.to(device)
        y = y.to(device)

        optimizer.zero_grad()

        outputs = model(t, i, a, v)

        loss = criterion(outputs, y)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} Loss: {total_loss:.4f}")

# ======================================================
# EVALUATION
# ======================================================

model.eval()

preds = []
truths = []

with torch.no_grad():

    for t, i, a, v, y in test_loader:

        t = t.to(device)
        i = i.to(device)
        a = a.to(device)
        v = v.to(device)

        outputs = model(t, i, a, v)

        pred = torch.argmax(outputs, dim=1).cpu().numpy()

        preds.extend(pred)
        truths.extend(y.numpy())

print("\nAccuracy:", accuracy_score(truths, preds))

print("\nClassification Report:")
print(classification_report(truths, preds))

# ======================================================
# SAVE MODEL
# ======================================================

torch.save(model.state_dict(), "gated_fusion_model.pth")

print("\nModel saved successfully!")

Using device: cpu
Loaded embeddings:
(43131, 768) (43131, 1280) (43131, 768) (43131, 768)
Epoch 1 Loss: 477.4247
Epoch 2 Loss: 361.3383
Epoch 3 Loss: 337.3082
Epoch 4 Loss: 324.4269
Epoch 5 Loss: 314.7522
Epoch 6 Loss: 308.9439
Epoch 7 Loss: 301.7813
Epoch 8 Loss: 297.6668
Epoch 9 Loss: 293.2164
Epoch 10 Loss: 288.6766

Accuracy: 0.8913875043468181

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.89      0.83      2501
           1       0.95      0.89      0.92      6126

    accuracy                           0.89      8627
   macro avg       0.86      0.89      0.87      8627
weighted avg       0.90      0.89      0.89      8627


Model saved successfully!

In [ ]:
# now use this embeddings for the basline models

In [ ]:
# Baseline 1 → Text embedding + BiLSTM
# Baseline 2 → Text embedding + Image embedding + Gated Fusion
# Proposed   → Cross-Attention Multimodal

In [ ]:
# text explainability

In [ ]:
# =========================================
# 1. IMPORTS
# =========================================
import pandas as pd
import torch
import torch.nn as nn
import shap
from sentence_transformers import SentenceTransformer
import random

# =========================================
# 2. DEVICE SETUP
# =========================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# =========================================
# 3. LOAD & CLEAN DATASET (FIXED)
# =========================================
df = pd.read_csv("balanced_multimodal_welfake.csv")

# Remove actual NaN values
df = df.dropna(subset=['text'])

# Convert to string
df['text'] = df['text'].astype(str)

# Remove invalid text entries
df = df[
    (df['text'].str.strip() != "") &
    (df['text'].str.lower() != "nan")
]

# Remove very short text (important for SHAP)
df = df[df['text'].str.len() > 20]

print("Clean dataset size:", len(df))

# =========================================
# 4. LOAD SBERT MODEL
# =========================================
sbert_model = SentenceTransformer('all-MiniLM-L6-v2', device=device)

# =========================================
# 5. DEFINE CLASSIFIER
# =========================================
class Classifier(nn.Module):
    def __init__(self, input_dim=384, hidden_dim=128, num_classes=2):
        super(Classifier, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        return x

classifier = Classifier().to(device)

# 🔴 LOAD YOUR TRAINED MODEL HERE
# classifier.load_state_dict(torch.load("model.pth", map_location=device))

classifier.eval()

# =========================================
# 6. PREDICTION FUNCTION (SAFE)
# =========================================
def predict(texts):
    # Extra safety cleaning
    texts = [
        str(t)[:300] if t and str(t).strip().lower() != "nan" else ""
        for t in texts
    ]

    embeddings = sbert_model.encode(
        texts,
        convert_to_tensor=True,
        device=device
    )

    with torch.no_grad():
        outputs = classifier(embeddings)
        probs = torch.softmax(outputs, dim=1)

    return probs.cpu().numpy()

# =========================================
# 7. SHAP EXPLAINER (STABLE SETTINGS)
# =========================================
explainer = shap.Explainer(
    predict,
    masker=shap.maskers.Text(),
    max_evals=20
)

# =========================================
# 8. SAFE SAMPLING
# =========================================
fake_texts = df[df['label'] == 1]['text'].tolist()
real_texts = df[df['label'] == 0]['text'].tolist()

def get_valid_samples(text_list, n=2):
    valid = [t for t in text_list if isinstance(t, str) and len(t.strip()) > 20]
    return random.sample(valid, min(n, len(valid)))

fake_samples = get_valid_samples(fake_texts)
real_samples = get_valid_samples(real_texts)

# =========================================
# 9. EXPLAIN FUNCTION (SAFE)
# =========================================
def explain_text(text, title=""):
    # Final safety check
    if text is None or str(text).strip() == "" or str(text).lower() == "nan":
        print("Skipping invalid text")
        return

    print("\n" + "="*60)
    print(title)
    print("="*60)
    print("\nTEXT:\n", text[:500])

    try:
        shap_values = explainer([text])
        shap.plots.text(shap_values[0])
    except Exception as e:
        print("SHAP failed for this sample:", e)

# =========================================
# 10. RUN EXPLANATIONS
# =========================================
print("\n========== FAKE NEWS EXAMPLES ==========")
for i, txt in enumerate(fake_samples):
    explain_text(txt, f"Fake Sample {i+1}")

print("\n========== REAL NEWS EXAMPLES ==========")
for i, txt in enumerate(real_samples):
    explain_text(txt, f"Real Sample {i+1}")

Using device: cpu
Clean dataset size: 18519

C:\Users\kruthi\.conda\New folder\envs\multimodal\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

========== FAKE NEWS EXAMPLES ==========

============================================================
Fake Sample 1
============================================================

TEXT:
 BREAKING: [VIDEO] Controversial Mayor Who Refused To Allow Sharia Law In Texas City Where Muslim Clock Boy Went To School Explains Why School Can’t Tell Their Side Of Story There s always another side that s usually being buried by the mainstream media in order to promote a leftist agenda Media coverage on Ahmed  Bomb-Clock  Mohamed has been remarkably one-sided, with the Mohamed family and the media spinning a tale of Islamophobia and overreaction.However, in an appearance on Glenn Beck s The B

============================================================
Fake Sample 2
============================================================

TEXT:
 Trump Gives 6 Reasons To Vote For Him Thursday, 3 November 2016 'VOTE FOR ME, WHAT HAVE YOU GOT TO LOSE?"
Donald Trump has given an amazing closing speech about why he should be elected President in 2016. It can be broken down into different parts about why he should be elected according to Mr. Trump:
1) "People say I suffer from a pathological narcissistic disorder, am a megalomaniac, assault women, and am a sociopath. Well, suppose all of this is true. It mostly isn't true of Bill Clinton an

========== REAL NEWS EXAMPLES ==========

============================================================
Real Sample 1
============================================================

TEXT:
 PsBattle: Donkey midsneeze

============================================================
Real Sample 2
============================================================

TEXT:
 Senator Johnson: Trump argued for repealing, replacing Obamacare WASHINGTON (Reuters) - U.S. President Donald Trump, at a lunch with Republican senators, argued for them to return to considering legislation to repeal and replace Obamacare instead of voting on a straight repeal, Senator Ron Johnson said. “That’s what the president was strongly arguing for,” Johnson told reporters after returning to the Capitol from the lunch at the White House. Johnson said he thought Senate leadership would like

In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

# =========================================
# LOAD DATA
# =========================================
df = pd.read_csv("balanced_multimodal_welfake.csv")

# If label is string, convert to numeric
if df["label"].dtype == object:
    df["label_num"] = df["label"].str.lower().map({"real": 0, "fake": 1})
else:
    df["label_num"] = df["label"].astype(int)

# =========================================
# LOAD EMBEDDINGS + MODEL
# =========================================
text_emb = np.load("text_embeddings.npy")
image_emb = np.load("image_embeddings.npy")
audio_emb = np.load("audio_embeddings.npy")
video_emb = np.load("video_embeddings.npy")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class MultimodalClassifier(nn.Module):
    def __init__(self, text_dim=768, image_dim=1280, audio_dim=768, video_dim=768, hidden_dim=256):
        super().__init__()
        self.text_proj = nn.Linear(text_dim, 128)
        self.image_proj = nn.Linear(image_dim, 128)
        self.audio_proj = nn.Linear(audio_dim, 128)
        self.video_proj = nn.Linear(video_dim, 128)

        self.classifier = nn.Sequential(
            nn.Linear(128 * 4, hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(hidden_dim, 2)
        )

    def forward(self, t, i, a, v):
        t = self.text_proj(t)
        i = self.image_proj(i)
        a = self.audio_proj(a)
        v = self.video_proj(v)

        x = torch.cat([t, i, a, v], dim=1)
        return self.classifier(x)

model = MultimodalClassifier().to(device)
model.load_state_dict(torch.load("multimodal_model.pth", map_location=device))
model.eval()

# =========================================
# PREDICTION FUNCTION
# =========================================
def predict_sample(idx):
    t = torch.tensor(text_emb[idx], dtype=torch.float32).unsqueeze(0).to(device)
    i = torch.tensor(image_emb[idx], dtype=torch.float32).unsqueeze(0).to(device)
    a = torch.tensor(audio_emb[idx], dtype=torch.float32).unsqueeze(0).to(device)
    v = torch.tensor(video_emb[idx], dtype=torch.float32).unsqueeze(0).to(device)

    with torch.no_grad():
        logits = model(t, i, a, v)
        probs = torch.softmax(logits, dim=1).cpu().numpy()[0]
        pred = int(np.argmax(probs))

    return pred, probs

# =========================================
# SHOW ONE FAKE + ONE REAL PER MODALITY GROUP
# =========================================
def show_examples_for_group(group_name):
    print("\n" + "="*80)
    print(f"MODALITY GROUP: {group_name}")
    print("="*80)

    subset = df[df["modality_group"] == group_name]

    for true_label, label_name in [(1, "FAKE"), (0, "REAL")]:
        row = subset[subset["label_num"] == true_label].sample(1, random_state=42)
        idx = row.index[0]

        pred, probs = predict_sample(idx)

        print("\n" + "-"*60)
        print(f"Ground Truth: {label_name}")
        print(f"Predicted   : {'FAKE' if pred == 1 else 'REAL'}")
        print(f"Confidence  : REAL={probs[0]:.4f}, FAKE={probs[1]:.4f}")
        print(f"Correct?    : {'YES' if pred == true_label else 'NO'}")
        print(f"Dataset idx : {idx}")

        text_value = str(df.loc[idx, "text"])[:700]
        print("\nTEXT:")
        print(text_value if text_value.strip() else "[No text available]")

        print("\nIMAGE PATH:")
        print(df.loc[idx, "image_path"])

        print("\nAUDIO PATH:")
        print(df.loc[idx, "audio_path"])

        print("\nVIDEO PATH:")
        print(df.loc[idx, "video_path"])

# Run for each group
show_examples_for_group("text_only")
show_examples_for_group("text_image")
show_examples_for_group("audio_video")

FileNotFoundError: [Errno 2] No such file or directory: 'balanced_multimodal_welfake.csv'